export default function createPDF(report) {
    console.log("Report Received:", report)
    const pdf = new window.jspdf.jsPDF();

    // Title
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(18);
    pdf.text("Accessibility Report", 105, 20, { align: "center" });

    // Subtitle
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);
    pdf.text("Generated by Accessibility Tracker", 105, 30, { align: "center" });

    // Summary Section
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Summary", 10, 50);

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Issues Found: ${report.totalIssues}`, 10, 60);
    pdf.text(`Pages Scanned: ${report.pagesScanned}`, 10, 70);
    
    
    pdf.setDrawColor(0); 
    pdf.setLineWidth(0.5);
    pdf.line(10, 80, 200, 80);

    // Issues Section
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Accessibility Issues", 10, 90);

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`1. Missing alt text on images: ${report.issues['missingAltText'].length}`, 10, 100);
    pdf.text(`2. Low contrast text: ${report.issues['lowContrast'].length}`, 10, 110);
    pdf.text(`3. Missing form labels: ${report.issues['missingLabels'].length}`, 10, 120);
    pdf.text(`4. Non-keyboard accessible elements: ${report.issues["nonKeyboardAccessible"].length}`, 10, 130);

    // Footer
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "italic");
    pdf.text("Report generated on: [Date Here]", 10, 280);
    pdf.text("© 2025 Accessibility Tracker", 105, 290, { align: "center" });

    // Save the PDF (for testing purposes)
    pdf.save("Accessibility_Report_Design.pdf");

}
