export default function createPDF(report) {
    console.log("Report Received:", report)
    const pdf = new window.jspdf.jsPDF();

    // Title
    pdf.setFillColor("#76b5c5"); // RGB for light blue
    pdf.rect(0, 0, 210, 32, 'F'); // Draw a filled rectangle (x, y, width, height)
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(30);
    pdf.setTextColor('#154c79')
    pdf.text("Accessibility Report", 105, 20, { align: "center" });

    // Subtitle
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(15);
    pdf.text("Generated by Zentry1", 105, 30, { align: "center" });

    // Summary Section
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.text("Summary", 10, 50);

    pdf.setFontSize(15);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Issues Found: ${report.totalIssues}`, 10, 60);
    pdf.text(`Pages Scanned: ${report.pagesScanned}`, 10, 70);


    // pdf.setDrawColor(0); 
    // pdf.setLineWidth(0.5);
    // pdf.line(10, 80, 200, 80);

    // Issues Section __
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.text("Accessibility Issues", 10, 90);
    // Styling For Title
    pdf.setFontSize(15);
    pdf.setFont("helvetica", "normal");
    // Text
    pdf.text(`1. Found ${report.issues['missingAltText'].length} images with missing alt text on `, 10, 100);
    // Styling For Tip
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Alt text helps users who rely on screen readers.`, 16, 107)
    // Styling For Title
    pdf.setFontSize(15);
    pdf.setFont("helvetica", "normal");
    pdf.text(`2. Found ${report.issues['lowContrast'].length} issues with low contrast `, 10, 114);
    // Styling For Tip
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Adequate contrast makes text readable for everyone.`, 16, 121)
    // Styling For Title
    pdf.setFontSize(15);
    pdf.setFont("helvetica", "normal");
    pdf.text(`3. Found ${report.issues['missingLabels'].length} forms with missing labels`, 10, 128);
    // Styling For Tip
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Clearly labeled form controls help user to know how to complete your form.`, 16, 135)
     // Styling For Title
    pdf.setFontSize(15);
    pdf.setFont("helvetica", "normal");
    pdf.text(`4. Found ${report.issues["nonKeyboardAccessible"].length} elements that are not accessible by keyboard`, 10, 142);
    // Styling For Tip
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Keyboard navigation is essential for users with motor impairments.`, 16, 149)


    // Footer
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "italic");
    pdf.text("Report generated on: [Date Here]", 10, 280);
    pdf.text("© 2025 Accessibility Tracker", 105, 290, { align: "center" });

    // Save the PDF (for testing purposes)
    pdf.save("Accessibility_Report_Design.pdf");

}
